{% set version = '%s_%04i_%s'|format(
    environ.get('GIT_DESCRIBE_TAG', 'v0.X'),
    environ.get('GIT_DESCRIBE_NUMBER', '0')|int,
    environ.get('GIT_DESCRIBE_HASH', 'gUNKNOWN')
    ) %}

package:
  name: openfpgaloader
  version: {{ version }}

source:
  git_url: https://github.com/trabucayre/openFPGALoader
  git_rev: master

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
    - libftdi
    - libusb
    - libhidapi
    - cmake
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
    - libftdi
    - libusb
    - libhidapi
    - cmake
  run:
    - libftdi
    - libusb
    - libhidapi

test:
  commands:
    - openFPGALoader -V

about:
  home: https://github.com/trabucayre/openFPGALoader
  license_file: LICENSE
  summary: 'Universal utility for programming FPGAs.'

extra:
  maintainers:
    - Tim 'mithro' Ansell <mithro@mithis.com>
    - HDMI2USB Project - https://hdmi2usb.tv <hdmi2usb@googlegroups.com>
