name: Build packages

on:
  workflow_call:
    secrets:
      ANACONDA_TOKEN:
        description: 'Anaconda Token'
      ANACONDA_USER:
        description: 'Anaconda User'

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  ANACONDA_USER: ${{ secrets.ANACONDA_USER }}

defaults:
  run:
    shell: bash

jobs:

  #1
  libusb-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "lib/usb"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #2
  libhidapi-linux:
    runs-on: "ubuntu-20.04"
    needs: "libusb-linux"
    env:
      PACKAGE: "lib/hidapi"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #3
  libxml2-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "lib/xml2"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #4
  icefunprog-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "tools/icefunprog"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #5
  flterm-linux:
    runs-on: "ubuntu-20.04"
    env:
      PACKAGE: "tools/flterm"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #6
  libftdi-linux:
    runs-on: "ubuntu-20.04"
    needs: "libusb-linux"
    env:
      PACKAGE: "lib/ftdi"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #7
  fxload-linux:
    runs-on: "ubuntu-20.04"
    needs: "libusb-linux"
    env:
      PACKAGE: "tools/fxload"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #8
  dfu-util-linux:
    runs-on: "ubuntu-20.04"
    needs: "libusb-linux"
    env:
      PACKAGE: "tools/dfu-util"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #9
  iceprog-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libusb-linux", "libftdi-linux"]
    env:
      PACKAGE: "tools/iceprog"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #10
  openocd-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libusb-linux", "libftdi-linux"]
    env:
      PACKAGE: "tools/openocd"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #11
  openfpgaloader-linux:
    runs-on: "ubuntu-20.04"
    needs: ["libusb-linux", "libftdi-linux", "libhidapi-linux"]
    env:
      PACKAGE: "tools/openfpgaloader"
      OS_NAME: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #12
  libusb-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "lib/usb"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #13
  libhidapi-osx:
    runs-on: "macos-latest"
    needs: "libusb-osx"
    env:
      PACKAGE: "lib/hidapi"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #14
  libxml2-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "lib/xml2"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #15
  icefunprog-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "tools/icefunprog"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #16
  flterm-osx:
    runs-on: "macos-latest"
    env:
      PACKAGE: "tools/flterm"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #17
  libftdi-osx:
    runs-on: "macos-latest"
    needs: "libusb-osx"
    env:
      PACKAGE: "lib/ftdi"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #18
  dfu-util-osx:
    runs-on: "macos-latest"
    needs: "libusb-osx"
    env:
      PACKAGE: "tools/dfu-util"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - run: brew install coreutils autoconf automake libtool
      - uses: hdl/conda-eda/ci@master

  #19
  iceprog-osx:
    runs-on: "macos-latest"
    needs: ["libusb-osx", "libftdi-osx"]
    env:
      PACKAGE: "tools/iceprog"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #20
  openocd-osx:
    runs-on: "macos-latest"
    needs: ["libusb-osx", "libftdi-osx"]
    env:
      PACKAGE: "tools/openocd"
      OS_NAME: "osx"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #21
  libusb-windows:
    runs-on: "windows-latest"
    env:
      PACKAGE: "lib/usb"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #22
  libhidapi-windows:
    runs-on: "windows-latest"
    needs: "libusb-windows"
    env:
      PACKAGE: "lib/hidapi"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #23
  libftdi-windows:
    runs-on: "windows-latest"
    needs: "libusb-windows"
    env:
      PACKAGE: "lib/ftdi"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master

  #24
  iceprog-windows:
    runs-on: "windows-latest"
    needs: ["libusb-windows", "libftdi-windows"]
    env:
      PACKAGE: "tools/iceprog"
      OS_NAME: "windows"
    steps:
      - uses: actions/checkout@v3
      - uses: hdl/conda-eda/ci@master
